name: Testing Technologies
favicon: null
layout_spectrum: 0.19953
typography_spectrum: 0.83556
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcb337'
    - '#ff0000'
    - '#ffff00'
    - '#808000'
    - '#000000'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
